include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - prefer_single_quotes
    - prefer_const_declarations
    - prefer_final_in_for_each
    - prefer_iterable_whereType
    - always_declare_return_types
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables

