name: animated_pin_input_text_field
description: A Flutter package for creating an animated and customizable pin/OTP input text field.
version: 0.0.1
homepage: https://github.com/tajaouart/animated_pin_input_text_field

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
